'''
Tracks cumulative downloads of fbi-data-api, designed to be run on GitHub Actions every day to update 
running total in ./downloads.json. Locally, run this script from this project's root directory.
'''
import json
import sys
import pypistats
from datetime import datetime, timezone
from pathlib import Path

PACKAGE = "fbi-data-api"
STATE_FILE = Path("./downloads.json")

def fetch_total_downloads() -> int:
    df = pypistats.overall(PACKAGE, mirrors = False, format = "pandas")
    
    return int(df.loc[df["category"] == "without_mirrors", "downloads"].iloc[0])

def fetch_downloads() -> dict:
    data = pypistats.recent(PACKAGE, format = "pandas")
    row = data.iloc[0]
    return {
        "last_day": int(row["last_day"]),
        "last_month": int(row["last_month"]),
    }

def load_state() -> dict:
    if STATE_FILE.exists():
        return json.loads(STATE_FILE.read_text())
    
    return None

def save_state(total: int, last_date: str) -> None:
    state = {
        "package": PACKAGE,
        "total_downloads": total,
        "last_date": last_date,
        "updated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "notes": "Do not edit this file manually. It is automatically updated by ./.github/workflows/track_downloads.yml every day."
    }
    
    STATE_FILE.write_text(json.dumps(state, indent = 2) + "\n")
    
    print(f"State written to {STATE_FILE}.")

def main():
    state = load_state()
    is_first_run = state is None

    running_total = 0 if is_first_run else state["total_downloads"]
    last_date = None if is_first_run else state["last_date"]
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    print(f"Fetching download history of '{PACKAGE}'...")

    if is_first_run:
        running_total = fetch_total_downloads()
        print(f"First run complete. The {PACKAGE} package has been downloaded a total of {running_total:,} times to date.")
    else:
        if last_date == today:
            print(f"Already ran today ({today}). Total downloads remain at {running_total:,}.")
            sys.exit(0)

        added = fetch_downloads()["last_day"]
        running_total += added
        print(
            f"Added {added:,} download(s) today. Total downloads are now at {running_total:,}."
        )

    save_state(running_total, today)

if __name__ == "__main__":
    main()
